### ISSUE TITLE
 obs screen recognition doesnt work  when open a ingame map

### ISSUE THREAD

**Issue by Elenedeath** [isaac-jordan/obs-screen-recognition#11]
Hello,
i try your script on my game with the newest update and when i open map ingame doesnt work but do the job on the deploy screen.

The bug is due to the incorrect mask, i dont know if it's my screen, new update or simply incorrect mask but i resolve by doing a new mask with the correct screen.

I send in attached file, the correct mask and my psd use to do it.
[mask-1080p.zip](https://github.com/isaac-jordan/obs-screen-recognition/files/5649088/mask-1080p.zip)
[mask-1440p.zip](https://github.com/isaac-jordan/obs-screen-recognition/files/5649622/mask-1440p.zip)

edit:
instead of pip install -r requirements.txt

the command used by people is python -m pip install -r requirements.txt
and in file requirements.txt you need to put or you get No matching distribution found on opencv
```
mss==6.1.0
numpy==1.19.3
obs-websocket-py==0.5.1
opencv-contrib-python==4.4.0.46
opencv-python==4.4.0.46
six==1.15.0
websocket-client==0.57.0
click==7.1.2
```

All packages are update to latest, only numpy are leave to 1.19.3 because a bug on latest numpy

the message when try to use latest numpy is
`RuntimeError: The current Numpy installation ('C:\\Python\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86`

**Comment by isaac-jordan** [comment]
Updated! Thanks for the mask files - real time saver. Thanks for the other feedback too, I've tested and updated them all.
